name: pantheon
description: $description
version: '${version}'

main: com.eclectusstudio.pantheon.Pantheon
api-version: '26.2'
load: POSTWORLD

authors: [Eclectusstudio]

commands:
  getitem:
    description: Gets a custom item.
    permission: pantheon.command.getitem
    usage: /getitem
