name: Pantheon
description: $description
version: '$version'

main: com.eclectusstudio.pantheon.Pantheon
api-version: '26.1.2'
load: POSTWORLD

authors: [Eclectus Studio]

commands:
  getitem:
    description: Gets a custom item.
    permission: pantheon.command.getitem
    usage: /getitem